// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210330161203_ProductTableUpdateqntdtoqtde")]
    partial class ProductTableUpdateqntdtoqtde
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataUltCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ValorUltVenda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<int>("qtde_estoque")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_unitario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ed7cd56-e02c-4357-8a8f-2bb40f9a0916"),
                            nome = "Bolo Do Adm",
                            qtde_estoque = 1,
                            valor_unitario = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
